# Generated by Django 3.2.6 on 2021-08-11 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=120, null=True)),
                ('construction', models.CharField(max_length=220, null=True)),
                ('fuel_type', models.CharField(max_length=220, null=True)),
                ('asset_location', models.CharField(max_length=220, null=True)),
                ('profile_Pic', models.ImageField(upload_to='user_profile')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
