# Generated by Django 3.2.6 on 2021-08-22 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, verbose_name='Please put your time')),
                ('reserved', models.BooleanField(default=False)),
                ('disel_price', models.IntegerField(default='1')),
                ('octen_price', models.IntegerField(default='1')),
                ('voucher', models.IntegerField(default='1')),
                ('promo_code', models.CharField(blank=True, max_length=40)),
                ('discount', models.IntegerField(default='1')),
                ('total_ammount', models.IntegerField(default='1')),
                ('delivery_charge', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='orderlimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Reserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=220)),
                ('company_name', models.CharField(blank=True, max_length=220)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=220)),
                ('area', models.CharField(max_length=220)),
                ('contact_photo', models.FileField(upload_to='contact_files')),
                ('city', models.CharField(max_length=300)),
                ('billing_add', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=220)),
                ('asset_type', models.CharField(max_length=220)),
                ('fuel_type', models.CharField(max_length=220)),
                ('asset_location', models.TextField(max_length=400)),
                ('asset_photo', models.FileField(upload_to='Asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
