# Generated by Django 3.2 on 2021-09-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='asset_location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='status',
            field=models.CharField(choices=[(1, 'PROCESSING'), (2, 'ON THE WAY'), (3, 'DELIVERED')], default=(1, 'PROCESSING'), max_length=30),
        ),
        migrations.DeleteModel(
            name='driver_dashboard',
        ),
    ]
