# Generated by Django 3.2.6 on 2021-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='profile_Pic',
            new_name='asset_pic',
        ),
        migrations.AddField(
            model_name='assets',
            name='area',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='billing_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='city',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='company_name',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='contact_pic',
            field=models.ImageField(default=1, upload_to='user_profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='email',
            field=models.EmailField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='full_name',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
