# Generated by Django 3.2 on 2021-09-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0002_auto_20210914_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='driver_status',
            field=models.CharField(default='Processing', max_length=30),
        ),
    ]
