# Generated by Django 3.2.6 on 2021-08-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0002_orderdashboard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdashboard',
            name='date',
            field=models.DateField(),
        ),
    ]
