# Generated by Django 3.2.6 on 2021-08-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0002_orderdashboard_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdashboard',
            old_name='user',
            new_name='client',
        ),
    ]
