# Generated by Django 3.2.6 on 2021-08-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0003_alter_orderdashboard_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdashboard',
            name='date',
        ),
    ]
