# Generated by Django 3.2.6 on 2021-08-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0003_assets_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='construction',
        ),
    ]
