# Generated by Django 3.2.6 on 2021-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0003_rename_user_orderdashboard_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdashboard',
            name='delivery_charge',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='discount',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='disel_price',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='octen_price',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='total_ammount',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='voucher',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
