# Generated by Django 3.2.6 on 2021-08-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0004_remove_orderdashboard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdashboard',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Uftl_App.orderdate'),
            preserve_default=False,
        ),
    ]
