# Generated by Django 3.2.6 on 2021-08-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0004_remove_assets_construction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
