# Generated by Django 3.2.6 on 2021-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0004_auto_20210822_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='cupon_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=40)),
                ('voucher', models.IntegerField(default='1')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdashboard',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='orderdashboard',
            name='voucher',
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='delivery_charge',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='discount',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='disel_price',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='octen_price',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='total_ammount',
            field=models.IntegerField(default='1'),
        ),
    ]
