# Generated by Django 3.2.6 on 2021-08-16 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Uftl_App', '0005_delete_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=220)),
                ('asset_type', models.CharField(max_length=220)),
                ('fuel_type', models.CharField(max_length=220)),
                ('asset_location', models.TextField(max_length=400)),
                ('asset_photo', models.FileField(upload_to='Asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
