# Generated by Django 3.2.6 on 2021-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0005_auto_20210822_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdashboard',
            name='discount',
        ),
        migrations.AddField(
            model_name='cupon_code',
            name='discount',
            field=models.IntegerField(default='1'),
        ),
    ]
