# Generated by Django 3.2.6 on 2021-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0006_auto_20210822_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon_code',
            name='promo_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
