# Generated by Django 3.2.6 on 2021-08-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0007_alter_cupon_code_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon_code',
            name='voucher',
        ),
    ]
