# Generated by Django 3.2.6 on 2021-08-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0007_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdashboard',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='time',
            field=models.TimeField(verbose_name='Please put your time'),
        ),
    ]
