# Generated by Django 3.2.6 on 2021-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0007_contact_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_assets',
            name='billing_add',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
