# Generated by Django 3.2.6 on 2021-08-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0008_auto_20210818_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdashboard',
            name='price',
            field=models.CharField(max_length=2),
        ),
    ]
