# Generated by Django 3.2.6 on 2021-08-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0008_remove_cupon_code_voucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cupon_code',
        ),
        migrations.AddField(
            model_name='orderdashboard',
            name='discount',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='orderdashboard',
            name='promo_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
