# Generated by Django 3.2.6 on 2021-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0008_contact_assets_billing_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_assets',
            name='city',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_assets',
            name='contact_photo',
            field=models.FileField(default=1, upload_to='contact_files'),
            preserve_default=False,
        ),
    ]
