# Generated by Django 3.2.6 on 2021-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0009_auto_20210822_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdashboard',
            name='delivery_charge',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='disel_price',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='octen_price',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='orderdashboard',
            name='total_ammount',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
