# Generated by Django 3.2.6 on 2021-08-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0010_reserved_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdashboard',
            name='price',
            field=models.CharField(default=False, max_length=2),
        ),
    ]
