# Generated by Django 3.2.6 on 2021-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0011_alter_orderdashboard_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdashboard',
            name='price',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
