# Generated by Django 3.2.6 on 2021-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0011_auto_20210822_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disel_price', models.IntegerField(default='1', null=True)),
                ('octen_price', models.IntegerField(default='1', null=True)),
                ('total_ammount', models.IntegerField(default='1', null=True)),
                ('delivery_charge', models.IntegerField(default='1', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdashboard',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='orderdashboard',
            name='disel_price',
        ),
        migrations.RemoveField(
            model_name='orderdashboard',
            name='octen_price',
        ),
        migrations.RemoveField(
            model_name='orderdashboard',
            name='total_ammount',
        ),
    ]
