# Generated by Django 3.2.6 on 2021-08-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0012_alter_orderdashboard_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserved',
            old_name='limit',
            new_name='slot',
        ),
    ]
