# Generated by Django 3.2.6 on 2021-08-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0012_auto_20210822_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='price',
            new_name='Fuel_price',
        ),
    ]
