# Generated by Django 3.2.6 on 2021-08-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0013_rename_limit_reserved_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserved',
            name='slot',
        ),
        migrations.AddField(
            model_name='orderdashboard',
            name='slot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
