# Generated by Django 3.2.6 on 2021-08-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0014_fuel_price_fuel_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_price',
            name='base_cost',
            field=models.IntegerField(default='1', max_length=10000),
        ),
    ]
