# Generated by Django 3.2.6 on 2021-08-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0015_remove_orderdashboard_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdashboard',
            name='time_slot',
            field=models.IntegerField(default='1'),
        ),
    ]
