# Generated by Django 3.2.6 on 2021-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0015_fuel_price_base_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_price',
            name='base_cost',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='fuel_price',
            name='fuel_ammount',
            field=models.IntegerField(default='1'),
        ),
    ]
