# Generated by Django 3.2.6 on 2021-08-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Uftl_App', '0016_auto_20210823_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel_price',
            old_name='fuel_ammount',
            new_name='fuel_amount',
        ),
        migrations.RenameField(
            model_name='fuel_price',
            old_name='total_ammount',
            new_name='total_amount',
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('asset_type', models.CharField(blank=True, max_length=300)),
                ('fuel_type', models.CharField(blank=True, max_length=300)),
                ('fuel_amount', models.IntegerField(default='1')),
                ('base_cost', models.IntegerField(default='1')),
                ('discount', models.IntegerField(default='1')),
                ('total_amount', models.IntegerField(default='1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
