# Generated by Django 3.2.6 on 2021-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0016_orderdashboard_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderlimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default='1')),
            ],
        ),
    ]
