# Generated by Django 3.2.6 on 2021-08-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0017_orderlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdashboard',
            name='price',
        ),
        migrations.AddField(
            model_name='orderdashboard',
            name='discount',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='orderdashboard',
            name='disel_price',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='orderdashboard',
            name='octen_price',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='orderdashboard',
            name='total_ammount',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='orderdashboard',
            name='voucher',
            field=models.IntegerField(default='1'),
        ),
    ]
