# Generated by Django 3.2.6 on 2021-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0017_auto_20210823_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
