# Generated by Django 3.2.6 on 2021-08-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0018_orderlist_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='delivery_method',
            field=models.CharField(max_length=300),
        ),
    ]
