# Generated by Django 3.2.6 on 2021-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0019_alter_orderlist_delivery_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='delivery_method',
            new_name='Cash_on_delivery',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='Online_Payment',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='Swipe_on_delivery',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
