# Generated by Django 3.2.6 on 2021-08-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0020_auto_20210823_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='Cash_on_delivery',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='Online_Payment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='Swipe_on_delivery',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
