# Generated by Django 3.2 on 2021-08-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0021_auto_20210823_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='Cash_on_delivery',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='Online_Payment',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='Swipe_on_delivery',
        ),
    ]
