# Generated by Django 3.2 on 2021-08-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0022_auto_20210823_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='asset_type',
            new_name='asset_name',
        ),
    ]
