# Generated by Django 3.2 on 2021-08-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0023_rename_asset_type_orderlist_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='order_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
