# Generated by Django 3.2.6 on 2021-08-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0028_alter_assets_asset_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_photo',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='contact_assets',
            name='contact_photo',
            field=models.ImageField(upload_to='contact_files'),
        ),
    ]
