# Generated by Django 3.2.6 on 2021-09-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0029_auto_20210826_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver_dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=220)),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uftl_App.orderlist')),
            ],
        ),
    ]
