# Generated by Django 3.2.6 on 2021-09-11 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Uftl_App', '0030_driver_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_dashboard',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
