# Generated by Django 3.2.6 on 2021-08-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfuel',
            old_name='fuel_ammount',
            new_name='fuel_amount',
        ),
    ]
