# Generated by Django 3.2.6 on 2021-08-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_rename_fuel_ammount_orderfuel_fuel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfuel',
            name='captcha',
            field=models.IntegerField(null=True),
        ),
    ]
