# Generated by Django 3.2.6 on 2021-08-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_orderfuel_captcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfuel',
            name='captcha',
        ),
    ]
