# Generated by Django 3.2.6 on 2021-08-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_remove_orderfuel_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_utils',
            name='construction_name',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
    ]
