# Generated by Django 3.2.6 on 2021-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_fuel_utils_construction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_utils',
            name='city',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
    ]
