# Generated by Django 3.2.6 on 2021-08-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_fuel_utils_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel_utils',
            old_name='construction_name',
            new_name='asset_type',
        ),
    ]
