# Generated by Django 3.2.6 on 2021-08-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0007_rename_construction_name_fuel_utils_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_utils',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='fuel_utils',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
