# Generated by Django 3.2.6 on 2021-08-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0009_fuel_utils_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_utils',
            name='asset_type',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='fuel_utils',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='fuel_utils',
            name='order_area',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
